
export const GET_TOURS = "GET_TOURS";
export const GET_TOUR = "GET_TOUR";
export const LANDING_PAGE = 'LANDING_PAGE';
export const HEART = 'HEART';
export const ALLHEART = 'ALLHEART';
export const CREATE_COMMENT = "CREATE_COMMENT";

// authentication and authorization
export const GET_USER = 'GET_USER';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const SIGNUP_FAIL = 'SIGNUP_FAIL';
export const SIGNUP_SUCCESS = 'SIGNUP_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const SET_ALERT = 'SET_ALERT';
export const REMOVE_ALERT = 'REMOVE_ALERT';
export const AUTHENTICATION_FAIL = "AUTHENTICATION_FAIL";
export const INITIAL_DATA = "INITIAL_DATA";
export const GET_BOOKING = "GET_BOOKING";
export const SET_EMAIL_VERIFY = "SET_EMAIL_VERIFY";
export const SET_NUMBER_VERIFY = "SET_NUMBER_VERIFY"
export const SET_DASHBOARD_LOGINED = 'SET_DASHBOARD_LOGINED'

//  addtowishlist
export const ADD_TO_WISHLIST = "ADD_TO_WISHLIST"

// carts constant
export const CART_ADD_ITEM = 'CART_ADD_ITEM'
export const CART_REMOVE_ITEM = 'CART_REMOVE_ITEM'
export const CART_SAVE_SHIPPING_ADDRESS = 'CART_SAVE_SHIPPING_ADDRESS'
export const CART_SAVE_PAYMENT_METHOD = 'CART_SAVE_PAYMENT_METHOD'
export const LOAD_CART_ITEM  = 'LOAD_CART_ITEM'
export const CART_UPDATE_PRICE = 'CART_UPDATE_PRICE' 
export const UPDATE_ORDER_ADDRESS = 'UPDATE_ORDER_ADDRESS'
export const LOAD_CART_ITEM_REQUEST = 'LOAD_CART_ITEM_REQUEST'

//export const REVIEW_LIKE = "REVIEW_LIKE";
export const REVIEW_LIKEDISLIKE = "REVIEW_DISLIKE";



// products
export const PRODUCT_LIST_REQUEST = 'PRODUCT_LIST_REQUEST'
export const PRODUCT_LIST_SUCCESS = 'PRODUCT_LIST_SUCCESS'
export const PRODUCT_LIST_FAIL = 'PRODUCT_LIST_FAIL'
// product list request
export const SELECT_CATEGORY_PRODUCT_REQUEST = 'SELECT_CATEGORY_PRODUCT_REQUEST'
export const SELECT_CATEGORY_PRODUCT_SUCCESS = 'SELECT_CATEGORY_PRODUCT_SUCCESS'

// getproductrequest
export const PRODUCT_REQUESTS_LIST_REQUEST = 'PRODUCT_REQUEST_LIST_REQUEST'
export const PRODUCT_REQUESTS_LIST_SUCCESS = 'PRODUCT_REQUESTS_LIST_SUCCESS'
export const LIVE_PRODUCT_REQUESTS_LIST = 'LIVE_PRODUCT_REQUESTS_LIST'

// homepage products
export const HOMEPAGE_PRODUCT_LIST_REQUEST = 'HOMEPAGE_PRODUCT_LIST_REQUEST'
export const HOMEPAGE_PRODUCT_LIST_SUCCESS = 'HOMEPAGE_PRODUCT_LIST_SUCCESS'
export const HOMEPAGE_PRODUCT_LIST_SUCCESS_MORE = 'HOMEPAGE_PRODUCT_LIST_SUCCESS_MORE'
export const HOMEPAGE_PRODUCT_LIST_SUCCESS_MORE_REQUEST = 'HOMEPAGE_PRODUCT_LIST_SUCCESS_MORE_REQUEST'
export const HOMEPAGE_PRODUCT_LIST_FAIL = 'HOMEPAGE_PRODUCT_LIST_FAIL'

//homepage packages
export const HOMEPAGE_PACKAGE_LIST_REQUEST = 'HOMEPAGE_PACKAGE_LIST_REQUEST'
export const HOMEPAGE_PACKAGE_LIST_SUCCESS = 'HOMEPAGE_PACKAGE_LIST_SUCCESS'

//homepage randomproducts
export const HOMEPAGE_RANDOM_PRODUCTS_REQUEST = 'HOMEPAGE_RANDOM_PRODUCTS_REQUEST'
export const HOMEPAGE_RANDOM_PRODUCTS_SUCCESS = 'HOMEPAGE_RANDOM_PRODUCTS_SUCCESS'

// filterd products
export const FILTERD_PRODUCT_LIST_REQUEST = 'FILTERD_PRODUCT_LIST_REQUEST'
export const FILTERD_PRODUCT_LIST_SUCCESS = 'FILTERD_PRODUCT_LIST_SUCCESS'
export const FILTERD_PRODUCT_LIST_SUCCESS_MORE = 'FILTERD_PRODUCT_LIST_SUCCESS_MORE'
export const FILTERD_PRODUCT_LIST_SUCCESS_MORE_REQUEST = 'FILTERD_PRODUCT_LIST_SUCCESS_MORE_REQUEST'
export const FILTERD_PRODUCT_LIST_FAIL = 'FILTERD_PRODUCT_LIST_FAIL'

// categories
export const CATEGORIES_LIST_REQUEST = "CATEGORIES_LIST_REQUEST"
export const CATEGORIES_LIST_SUCCESS = "CATEGORIES_LIST_SUCCESS"
export const CATEGORY_REQUEST = 'CATEGORY_REQUEST'
export const CATEGORY_SUCCESS = "CATEGORY_SUCCESS"
export const CATEGORIES_LIST_FAIL = "CATEGORIES_LIST_FAIL"

// scales
export const SCALE_LIST_REQUEST = 'SCALE_LIST_REQUEST'
export const SCALE_LIST_SUCCESS = 'SCALE_LIST_SUCCESS'

// Users 
export const GET_USERS_REQUEST = "GET_USERS_REQUEST"
export const GET_USERS_SUCCESS = "GET_USERS_SUCCESS"
export const CREATE_USER_RESULT = "CREATE_USER_RESULT"
export const USER_CREATED = 'USER_CREATED'

export const GET_USER_REQUEST = "GET_USER_REQUEST"
export const GET_USER_SUCCESS = "GET_USER_SUCCESS"

// notifications
export const ADD_NOTIFICATION = "ADD_NOTIFICATION"
export const REMOVE_NOTIFICATION = "REMOVE_NOTIFICATION"
export const LOAD_NOTIFICATION = "LOAD_NOTIFICATION"

// site settings
//export const ADMIN_UPDATE_LOGO_SETTINGS_REQUEST = 'ADMIN_UPDATE_LOGO_SETTINGS_REQUEST'
//export const ADMIN_UPDATE_LOGO_SETTINGS_SUCCESS = 'ADMIN_UPDATE_LOGO_SETTINGS_SUCCESS'
export const ALL_SETTINGS_REQUEST = 'ALL_SETTINGS_REQUEST'
export const ALL_SETTINGS = 'ALL_SETTINGS'

// Roles
export const ROLES_ACCESS_REQUEST = 'ROLES_ACCESS_REQUEST'
export const ROLES_ACCESS_LIST =  'ROLES_ACCESS_LIST'
export const SPECIFIC_ROLE_REQUEST = 'SPECIFIC_ROLE_REQUEST'
export const SPECIFIC_ROLE_SUCCESS = 'SPECIFIC_ROLE_SUCCESS'

export const PRODUCT_DETAILS_REQUEST = 'PRODUCT_DETAILS_REQUEST'
export const PRODUCT_DETAILS_SUCCESS = 'PRODUCT_DETAILS_SUCCESS'
export const PRODUCT_DETAILS_FAIL = 'PRODUCT_DETAILS_FAIL'


//Admin Orders
export const ADMIN_DAILY_ORDER_REQUEST = 'ADMIN_DAILY_ORDER_REQUEST'
export const ADMIN_DAILY_ORDER_SUCCESS = 'ADMIN_DAILY_ORDER_SUCCESS'
export const UPDATE_DAILY_ORDER_LIVE = 'UPDATE_DAILY_ORDER_LIVE'

// dashboard
export const ADMIN_DASHBOARD_REQUEST = 'ADMIN_DASHBOARD_REQUEST'
export const ADMIN_DASHBOARD_SUCCESS = 'ADMIN_DASHBOARD_SUCCESS'

export const GET_VENDOR_RIDERS = 'GET_VENDOR_RIDERS'

export const PRODUCT_DELETE_REQUEST = 'PRODUCT_DELETE_REQUEST'
export const PRODUCT_DELETE_SUCCESS = 'PRODUCT_DELETE_SUCCESS'
export const PRODUCT_DELETE_FAIL = 'PRODUCT_DELETE_FAIL'

export const PRODUCT_CREATE_REQUEST = 'PRODUCT_CREATE_REQUEST'
export const PRODUCT_CREATE_SUCCESS = 'PRODUCT_CREATE_SUCCESS'
export const PRODUCT_CREATE_FAIL = 'PRODUCT_CREATE_FAIL'
export const PRODUCT_CREATE_RESET = 'PRODUCT_CREATE_RESET'

export const PRODUCT_UPDATE_REQUEST = 'PRODUCT_UPDATE_REQUEST'
export const PRODUCT_UPDATE_SUCCESS = 'PRODUCT_UPDATE_SUCCESS'
export const PRODUCT_UPDATE_FAIL = 'PRODUCT_UPDATE_FAIL'
export const PRODUCT_UPDATE_RESET = 'PRODUCT_UPDATE_RESET'

export const PRODUCT_CREATE_REVIEW_REQUEST = 'PRODUCT_CREATE_REVIEW_REQUEST'
export const PRODUCT_CREATE_REVIEW_SUCCESS = 'PRODUCT_CREATE_REVIEW_SUCCESS'
export const PRODUCT_CREATE_REVIEW_FAIL = 'PRODUCT_CREATE_REVIEW_FAIL'
export const PRODUCT_CREATE_REVIEW_RESET = 'PRODUCT_CREATE_REVIEW_RESET'

export const PRODUCT_TOP_REQUEST = 'PRODUCT_TOP_REQUEST'
export const PRODUCT_TOP_SUCCESS = 'PRODUCT_TOP_SUCCESS'
export const PRODUCT_TOP_FAIL = 'PRODUCT_TOP_FAIL'

// search products
export const SEARCH_PRODUCT_LIST_REQUEST = 'SEARCH_PRODUCT_LIST_REQUEST'
export const SEARCH_PRODUCT_LIST_SUCCESS = 'SEARCH_PRODUCT_LIST_SUCCESS'
export const SEARCH_PRODUCT_LIST_SUCCESS_MORE = 'SEARCH_PRODUCT_LIST_SUCCESS_MORE'
export const SEARCH_PRODUCT_LIST_SUCCESS_MORE_REQUEST = 'SEARCH_PRODUCT_LIST_SUCCESS_MORE_REQUEST'
export const SEARCH_PRODUCT_LIST_FAIL = 'SEARCH_PRODUCT_LIST_FAIL'
// orders

export const ORDER_CREATE_REQUEST = 'ORDER_CREATE_REQUEST'
export const ORDER_CREATE_SUCCESS = 'ORDER_CREATE_SUCCESS'
export const ORDER_CREATE_FAIL = 'ORDER_CREATE_FAIL'

export const ORDER_DETAILS_REQUEST = 'ORDER_DETAILS_REQUEST'
export const ORDER_DETAILS_SUCCESS = 'ORDER_DETAILS_SUCCESS'
export const ORDER_DETAILS_FAIL = 'ORDER_DETAILS_FAIL'

export const ORDER_PAY_REQUEST = 'ORDER_PAY_REQUEST'
export const ORDER_PAY_SUCCESS = 'ORDER_PAY_SUCCESS'
export const ORDER_PAY_FAIL = 'ORDER_PAY_FAIL'
export const ORDER_PAY_RESET = 'ORDER_PAY_RESET'

export const ORDER_LIST_MY_REQUEST = 'ORDER_LIST_MY_REQUEST'
export const ORDER_LIST_MY_SUCCESS = 'ORDER_LIST_MY_SUCCESS'
export const ORDER_LIST_MY_FAIL = 'ORDER_LIST_MY_FAIL'
export const ORDER_LIST_MY_RESET = 'ORDER_LIST_MY_RESET'

export const ORDER_LIST_REQUEST = 'ORDER_LIST_REQUEST'
export const ORDER_LIST_SUCCESS = 'ORDER_LIST_SUCCESS'
export const ORDER_LIST_FAIL = 'ORDER_LIST_FAIL'

export const ORDER_DELIVER_REQUEST = 'ORDER_DELIVER_REQUEST'
export const ORDER_DELIVER_SUCCESS = 'ORDER_DELIVER_SUCCESS'
export const ORDER_DELIVER_FAIL = 'ORDER_DELIVER_FAIL'
export const ORDER_DELIVER_RESET = 'ORDER_DELIVER_RESET'

